cookie:
  expiry_days: 0
  key: random_signature_key # Must be string
  name: random_cookie_name
credentials:
  usernames:
    incar_edu:
      email: incar_edu@incar.co.kr
      name: incar edu
      password: $2b$12$PKTu/QXqidR29c63jHT68ueMw9kiZZNY0N1yMuwRs2j/Ijn5bReZ6
preauthorized:
  emails:
  - hun2up@gmail.com